FileApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="file"
urlpatterns = [
    path('file_list/<str:proj_Code>', views.show_file_list, name="file_list"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
    #path('create_invite_url/<str:pro_code>', views.create_invite_url, name="invite"),
    path('add_notice/', views.add_notice, name='add_notice')
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views
import explorer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
    #path('explorer/', include('explorer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

UserApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('mypage/',views.mypage,name='mypage'),
    path('logout/',views.logout,name='logout'),
    path('accept_project/',views.join_project,name='join_project'),
    path('cofirm_alarm/',views.cofirm_alarm,name='cofirm_alarm'),
]

UserApp/models.py
import string
from random import choice

from colorfield.fields import ColorField
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from ProjectApp.models import Projects

media_path = settings.MEDIA_ROOT

def user_path(instance,filename):
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return 'profiles/%s.%s' % (pid, extension)
    

class Profile(models.Model):
    objects = models.Manager()
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name='Profile')
    nickname = models.CharField(max_length=50, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(upload_to = user_path,blank=True,default='profiles\default_profile.png')
    user_color = ColorField(default='#FF0000')


@receiver(post_save,sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.Profile.save()
# receiver는 이벤트가 발생 할 때 찾는 놈입니다. 
# save가 발생 할 때 마다 create_user_profile/save_user_profile로 Profile도 같이 생성되게 하는 놈이에여
# 결론 = 지우지마!

class Dashboard_User(models.Model):
    objects = models.Manager()
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nodes = models.IntegerField(default=0)
    contribution = models.FloatField(default=0)
    comments = models.IntegerField(default=0)

UserApp/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password','first_name','last_name']
        
# user의 기본 기능은 더 있습니다! 없을경우 profileform에 추가하기

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio','location','birth_date']

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

UserApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import auth
from .models import Profile
from ProjectApp.models import Projects
from .forms import UserForm, ProfileForm, LoginForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from notifications.signals import notify
# Create your views here.

def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            # user_form = UserForm(request.POST)
            profile_form = ProfileForm(request.POST)
            # user_form_password = request.POST['password']
            # user = user_form.save()
            # user.set_password(user_form_password)
            # user.save()
            if profile_form.is_valid():
                #이 밑에 저거 왜 필요한지 모르겠어서 일단 주석해둘게요 ,, 
                '''
                user.profile.bio = profile_form.cleaned_data.get('bio')
                user.profile.location = profile_form.cleaned_data.get('location')
                user.profile.save()
                '''
                user.Profile.nickname = request.POST['username']
                auth.login(request, user)
                redirect('project:project_list')
            else:
                return redirect('user:login')
        return render(request,'ProjectApp/project_list.html')

    elif request.method == 'GET':
        user_form = UserForm()
        profile_form = ProfileForm()
        return render(request,'UserApp/signup.html',{'user_form':user_form,'profile_form':profile_form})
    else:
        return render(request,'ProjectApp/project_list.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None: #스무스하게 로그인
            auth.login(request, user)
            return redirect('project:project_list')
        else: #뭔가 잘못쳤을 때
            return redirect('index')


            # hidden = 0
            # message = "로그인 정보가 옳지 않아요!"
            # return render(request,'MainApp/index.html',{'hidden':hidden,'message':message})
    else:
        login_form = LoginForm()
        return render(request,'UserApp/login.html',{'login_form':login_form})

def logout(request):
    auth.logout(request)
    return redirect('index')

def mypage(request):
    recipients = User.objects.all()
    user = request.user
    if user in recipients:
        unread_messages = user.notifications.unread()
        unread_messages_invite = unread_messages.filter(description = 1)
        # for i in unread_messages_invite:
        #     invite_code = i.verb
        #     project_name = Projects.objects.get(Code = invite_code)
            # i.append({'project_name':project_name})
            # print(i)
        print(unread_messages_invite)
        unread_messages_invite_return = unread_messages.filter(description = 2)
        return render(request,'UserApp/mypage.html',{'unread_messages':unread_messages,'unread_messages_invite':unread_messages_invite,'unread_messages_invite_return':unread_messages_invite_return})
    return render(request,'UserApp/mypage.html',{})

def join_project(request):
    recipient = request.user
    actor = User.objects.get(username=request.POST['actor'])
    project = request.POST['project']
    proj_request = recipient.notifications.filter(verb=project)
    if request.method == 'POST':
        for i in proj_request:
            if actor == i.actor:
                print(project)
                notify.send(request.user,recipient = i.actor,verb = request.user.username+'님이'+project+"참가를 허용하셨습니다!", description = 2 )
                i.mark_as_read()
                join_project = Projects.objects.get(Code = project)
                join_project.members.add(i.actor)
                join_project.save()
        # User_Profile = Profile.objects.get(user=actor)
        # User_Profile.projects += ','+project
        # User_Profile.save()
        return redirect('user:mypage')
    else:
        for i in proj_request:
            if actor == i.actor:
                i.mark_as_read()
        return redirect('user:mypage')
    

def cofirm_alarm(request):
    recipient = request.user
    actor = User.objects.get(username=request.POST['actor'])
    project = request.POST['project']
    proj_request = recipient.notifications.filter(verb=project)
    if request.method == 'POST':
        for i in proj_request:
            if actor == i.actor:
                i.mark_as_read()
        return redirect('user:mypage')
        
    return redirect('user:mypage')

UserApp/templates/UserApp/login.html
{% load sass_tags %}
{% load static %}
{% block scss %}
    <link href="{% sass_src 'UserApp/CSS/LoginForm.scss' %}" rel="stylesheet" type="text/css">
    <link rel="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock %}
{% block content %}
<div class="loginModal">
    <div class="modal_Overlay"></div>
    <div class="modal_Contents">
        <form method="POST" action="{% url 'user:login' %}" class="login">
            {% csrf_token %}
            <img src="{% static 'MainApp/image/fn_logo.png' %}" alt="로고" class="login_logo loginbox">
            <input class="loginbox" type="text" name="username" placeholder="아이디">
            
            <input class="loginbox" type="password" name="password" placeholder="비밀번호">

            <span class="ToGoSignup">아직 계정이 없다면? <a class="ToGoSignup_A" href="#" onclick="alert('클로즈베타 기간(2021.05.24~2021.06.30) 동안 가입이 불가능합니다.')">가입하기</a></span>
            <button class="loginbox" type="submit">Log in</button>
            <br>
        </form>   
    </div>
</div>


<!-- <div class="all">
    <form method="POST" action="{% url 'user:login' %}">
        {% csrf_token %}
        <p>username</p>
        <input class="loginbox" type="text" name="username">
        <br>
        <p>password</p>
        <input class="loginbox" type="text" name="password">
        <br>
        <input class="loginbtn" type="submit" value="로그인">
        
    </form>        
</div> -->
{% endblock %}
{% block JS %}
{% endblock %}

UserApp/templates/UserApp/mypage.html
{% extends 'base.html' %}
{% load sass_tags %}
{% load notifications_tags %}
{% load static %}
{% block scss %}
<link href="{% sass_src 'UserApp/CSS/mypage.scss' %}" rel="stylesheet" type="text/css">

{% endblock %}

{% block leftbar %}
<div class="side-box">
    <p class="side-title">내 프로젝트</p>
    {% for project in proj_obj %}
    <ul class="side-content">
        <li class="side-project-name"><a href="{% url 'file:file_list' project.id %}" style="color: black">
                <p>프로젝트{{project.id}} : {{project.name}}</p>
            </a></li>
    </ul>
    {% endfor %}
</div>

<div class="side-box">
    <p class="side-title ">최종 파일 모음</p>
</div>
{% endblock %}


{% block content %}
{% notifications_unread as unread_count %}
<!-- <button>구독 신청하기(과금)</button> -->
<div class="big-box">
    <!--hidden-->
    <div class="modal_Overlay"></div>
    <div class="modal_Contents">
        <div class="upload_Form">
            <div class="noti">
                <div class="noti-title">
                    {% if unread_count %}
                    {{unread_count}}개의 새 알림이 있습니다.
                    {% else %}
                    새 알림이 없네요!
                    {% endif %}
                </div>
            </div>

            {% if unread_messages_invite %}
            <div class="box">
                {{invite_project}}
                {% for unread_messages in unread_messages_invite.all %}
                <div class="title">
                    {{unread_messages.actor}}님 께서<br>"{{unread_messages.verb}}" 프로젝트 참가를 원하십니다!
                </div>
                <form class="submit" action="{% url 'user:join_project' %}" method='POST'>
                    {% csrf_token %}
                    <input type='hidden' name='actor' value='{{unread_messages.actor}}'>
                    <input type='hidden' name='project' value='{{unread_messages.verb}}'>
                    <input class="uploadBtn" type='submit' value='수락'>
                </form>
                <form class="submit" action="{% url 'user:cofirm_alarm' %}" method='POST'>
                    {% csrf_token %}
                    <input type='hidden' name='actor' value='{{unread_messages.actor}}'>
                    <input type='hidden' name='project' value='{{unread_messages.verb}}'>
                    <input class="uploadBtn" type='submit' value='거절'>
                </form>
                {% endfor %}
            </div>
            {% endif %}

            {% if unread_messages_invite_return %}
            <div class="box">
                {% for unread_messages in unread_messages_invite_return.all %}
                <div class="title">
                    {{unread_messages.verb}}
                </div>
                <form class="submit" action="{% url 'user:cofirm_alarm' %}" method='POST'>
                    {% csrf_token %}
                    <input type='hidden' name='actor' value='{{unread_messages.actor}}'>
                    <input type='hidden' name='project' value='{{unread_messages.verb}}'>
                    <input class="uploadBtn" type='submit' value='확인'>
                </form>

                {% endfor %}
            </div>
            {% endif %}

        </div>




    </div>
</div>

{% endblock %}
{% block JS %}
{% endblock %}

UserApp/templates/UserApp/signup.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% sass_src 'UserApp/CSS/signup.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="all">
        <img class="logo" src="{% static 'MainApp/image/fn_logo.png'%}" alt="">
        <form method="POST" action="{% url 'user:signup' %}" class="login">
            {% csrf_token %}
            <span class="signup_text">아이디</span>
            <input class="loginbox" type="text" name="username" required autofocus/>
            
            <span class="signup_text">비밀번호</span>
            <input class="loginbox" type="Password" name="password" required>
            
            <span class="signup_text">비밀번호 확인</span>
            <input class="loginbox" type="Password" name="confirm" required>
            
            <button class="spinner" type="submit">Sign up</button>
        </form>        
    </div>
</body>
</html>