FileApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="file"
urlpatterns = [
    path('file_list/<str:proj_Code>', views.show_file_list, name="file_list"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
    #path('create_invite_url/<str:pro_code>', views.create_invite_url, name="invite"),
    path('add_notice/', views.add_notice, name='add_notice')
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views
import explorer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
    #path('explorer/', include('explorer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MainApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout"),
]

ProjectApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('project_list/', views.show_project_list, name="project_list"),
    path('project_detail/', views.show_project_detail, name="project_detail"),
    path('project_checkcode/',views.project_checkcode, name='project_checkcode'),
    path('project_create',views.project_create,name='project_create'),
    path('project_likeornot/<str:project_Code>',views.likeornot,name='project_likeornot'),
    path('error/', views.error, name='error'),
    path('create/<str:project_Code>', views.create_invite_url, name='create_invite_url'),
    path('invite/<str:project_Code>', views.confirm_project_checkin, name='confirm_project_checkin'),
    path('project_checkin/', views.project_checkin, name='project_checkin'),
    path('already_exist/', views.already_exist, name='already_exist'),
    # path('proj_contributions/<str:project_Code>',views.proj_contributions, name = 'proj_contributions'),

    # path('form_create_project/', views.form_create_project, name="form_create_project"),
    # path('create_project/', views.create_project, name="create_project"),
]

UserApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('mypage/',views.mypage,name='mypage'),
    path('logout/',views.logout,name='logout'),
    path('accept_project/',views.join_project,name='join_project'),
    path('cofirm_alarm/',views.cofirm_alarm,name='cofirm_alarm'),
]

MainApp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

MainApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# 자동로그인
def index(request):
    return render(request, 'MainApp/index.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('index')
    return render(request, 'MainApp/index.html')
    

MainApp/templates/Base/base_before.html
<!-- sass 불러오는 태그 -->
{% load sass_tags %}
<!-- end -->
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FromNode</title>
    <link href="{% sass_src 'MainApp/CSS/Base/style.scss' %}" rel="stylesheet" type="text/css">
    <!-- 멘션을 위한 source -->
    <link href="{% sass_src 'MainApp/CSS/Base/tribute.scss' %}" rel="stylesheet">
    <script src="{% static 'MainApp/JS/tribute.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- scss를 선언할 영역 -->
    {% block scss %}
    {% endblock %}
    
    {% block inlineCss %}
    {% endblock %}
    <!-- end -->
</head>

<body>
{% if user.is_authenticated %}
    <!--상단부-->
        <div class="top">
            <div class="top_nav">
                <!-- 로고 -->
                <div class="box-left">
                    <a class="box-left" href="{% url 'project:project_list' %}">
                        <img class="logo" src="{% static 'MainApp/image/fn_logo.png'%}" alt="로고">
                    </a>
                </div>

                <div class="box-center">
                    <form class="search" action="http://www.google.com" method='GET'>
                        <input class="input_box" type="text" name="query" placeholder="Search">
                        <div class="input_button">
                            <input class="find_img" type="image" src="{% static 'MainApp/image/search.png' %}" alt="Submit">
                        </div>
                    </form>
                </div>


                <!-- 유저 도구 -->
                <!-- <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a href="#"><img class="icon" src="{% static 'image/grid.png'%}" alt=""></a></li>
                        <li class="nav-item"><a href="#"><img class="icon" src="{% static 'image/bell.png'%}" alt=""></a></li>
                        <li class="icon-dropdown nav-item"><a href="#"><img class="icon-profile" src="{% static 'image/logo_character.png' %}" alt=""></a></li>
                    </ul>
                </div> -->
                <div class='box-right'>
                    <ul class="nav-box">
                        <!-- <li class="nav-item"><a href="#"><img class="icon" src="{% static 'Mainapp/image/grid.png' %}" alt=""></a></li>
                        <li class="nav-item"><a href="{% url 'user:mypage' %}"><img class="icon" src="{% static 'Mainapp/image/bell.png' %}" alt=""></a></li>
                        <li class="icon-dropdown nav-item"><a href="{% url 'user:logout' %}"><img class="icon-profile" src="{% static 'Mainapp/image/logo_character.png' %}" alt=""></a></li> -->
                        <li class="nav-item">
                            <a class="nav-item" href="{% url 'user:mypage' %}">
                                <img class="Bell_logo" src="{% static 'MainApp/image/alarm.png'%}" alt="마이페이지">
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-item"
                                href="javascript:{document.getElementById('logout').submit()}">Logout</a>
                            <form id="logout" method="POST" action="{% url 'logout' %}">
                                {% csrf_token %} <input type="hidden" />
                            </form>
                        </li>
                        


                    </ul>
                </div>
                <!-- 사용자 모델에서 이미지를 가지고 와야하는데 말이야 .. 음 .. base.html이 연결되는 view를 만들어서
                            그 view에 유저 프로필 사진을 ~로 담아서 보내야겠다. -->
            </div>
        </div>
        <div class="bottom">
<!-- 왼쪽 메뉴 -->
            <div class="left-menu">
                <div class="left-menu-guide">
                    <div class="side-box">
                        <p class="side-title">내 프로젝트</p>
                        {% for project in proj_obj_all %}
                        <ul class="side-content">
                            <li class="side-project-name">
                                <a href="{% url 'file:file_list' project.id %}"
                                    style="color: white;">
                                    <p>{{project.name}}</p>
                                </a></li>
                        </ul>
                        {% endfor %}
                    </div>

                    <div class="side-box">
                        <p class="side-title ">최종 파일 모음</p>
                    </div>
                    <!-- leftbar -->
                    <!-- endblock -->
                </div>
            </div>

            <div class="content">
                <div class="content-guide">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

        </div>
    {% block JS %}
    {% endblock %}
{% endif %}
</body>

</html>

MainApp/templates/Base/mention_block.html
{% load static %}

<body>
{% if user.is_authenticated %}
    <mini-editor placeholder="내용을 입력하세요 (@멘션)"  ></mini-editor>
{% endif %}
</body>

<script src="{% static 'MainApp/JS/mention_block.js' %}">
</script>

<!-- django 의 include 사용해서 원하는 곳에 갖다 쓰기 ! -->

MainApp/templates/Base/testbase2.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FromNode</title>
    <link rel="stylesheet" href="{% static 'MainApp/CSS/Base/leftbar.css'%}" type="text/css">
    <link href="{% sass_src 'MainApp/CSS/Base/test.scss' %}" rel="stylesheet" type="text/css">

    <!-- scss를 선언할 영역 -->
    {% block scss %}
    {% endblock %}
</head>

<body>
    <!--상단부-->
    <div class="container">
        <div class="top">
                <div class="top_left">
                    <a href="{% url 'project:project_list' %}">
                        <img src="{% static 'MainApp/image/logo_image_text.png'%}" alt="">
                    </a>
                </div>
                <div class="top_center">
                    <form class="search_form" action="#" method='GET'>
                        <input class="searchInput" type="text" name="query" placeholder="Search">
                        <div class="input_button">
                            <input class="search_img" type="image" src="{% static 'MainApp/image/find.png' %}" alt="Submit">
                        </div>
                    </form>
                </div>
                <div class="top_right">
                    <ul>
                        <li class="nav-item"><a class="nav-item" href="javascript:{document.getElementById('logout').submit()}">Logout</a>
                            <form id="logout" method="POST" action="{% url 'logout' %}">
                                {% csrf_token %}   
                                <input type="hidden" />
                            </form>
                        </li>
                    </ul>
                </div>
        </div>
        <div class="bottom">
            <div class="left_nav">
                {% block leftbar %}
                {% endblock %}
            </div>
            <Div class="main_contents">
                {% block content %}
                {% endblock %}
            </Div>
        </div>
    </div>
    {% block JS %}
    {% endblock %}
</body>

</html>