FileApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="file"
urlpatterns = [
    path('file_list/<str:proj_Code>', views.show_file_list, name="file_list"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
    #path('create_invite_url/<str:pro_code>', views.create_invite_url, name="invite"),
    path('add_notice/', views.add_notice, name='add_notice')
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views
import explorer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
    #path('explorer/', include('explorer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

MainApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout"),
]

ProjectApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('project_list/', views.show_project_list, name="project_list"),
    path('project_detail/', views.show_project_detail, name="project_detail"),
    path('project_checkcode/',views.project_checkcode, name='project_checkcode'),
    path('project_create',views.project_create,name='project_create'),
    path('project_likeornot/<str:project_Code>',views.likeornot,name='project_likeornot'),
    path('error/', views.error, name='error'),
    path('create/<str:project_Code>', views.create_invite_url, name='create_invite_url'),
    path('invite/<str:project_Code>', views.confirm_project_checkin, name='confirm_project_checkin'),
    path('project_checkin/', views.project_checkin, name='project_checkin'),
    path('already_exist/', views.already_exist, name='already_exist'),
    # path('proj_contributions/<str:project_Code>',views.proj_contributions, name = 'proj_contributions'),

    # path('form_create_project/', views.form_create_project, name="form_create_project"),
    # path('create_project/', views.create_project, name="create_project"),
]

UserApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('mypage/',views.mypage,name='mypage'),
    path('logout/',views.logout,name='logout'),
    path('accept_project/',views.join_project,name='join_project'),
    path('cofirm_alarm/',views.cofirm_alarm,name='cofirm_alarm'),
]

MainApp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

MainApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# 자동로그인
def index(request):
    return render(request, 'MainApp/index.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('index')
    return render(request, 'MainApp/index.html')
    

MainApp/templates/MainApp/base.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FromNode</title>
    <!-- <link rel="stylesheet" href="{% static 'baseTemplates/CSS/style.css' %}"> -->
    <style>
        * {
        margin: 0;
        padding: 0;
        }

        a { color: #000; }
        a:link { color: black; }
        a:visited { color: black; }

        /* 전체 구조 */
        body{
        background: white;
        margin: 0;
        display: flex;
        justify-content: center;
        }

        .container{
        display: flex;
        flex-direction: column;

        }

        /* 상단 바 */
        .top{
        /* position:absolute;
        top:50%;
        left:50%;
        background: white;
        transform:translate(-50%, -50%); */
        width: 100%;
        height: auto;
        }

        .content{
        display: flex;
        flex-direction: column;
        width: 100%;
        padding: 25px 0;

        }

        /* 끝 */

        /* 상단 네브바 */
        .top_nav{
        height: 120px;
        display: flex;
        background-color: white;
        border-bottom: solid 1px black;
        position: relative;
        }

        .box-left { 
        /* flex: 0.5; */
        width: 300px;
        padding: 25px 0;
        font-size: 1.3rem;
        display: flex;
        justify-content: center;
        align-items: center;
        }

        .logo_img{
        height: auto;
        width: 100px;
        }



        .box-center {
        flex: 1.4;
        text-align: left;
        padding: 30px 0;
        display: flex;
        align-items: center;
        }

        input:focus{
        outline:none;
        }
        .input_box{
        padding: 20px;
        border: 1.8px solid #004077;
        border-radius : 30px; 
        width:680px;
        height:15px;            
        font-size: 17px;
        }

        .input_button{
        /* padding: 20px; */
        width: 60px;
        height: 43px;
        border: 1px solid black;
        border-radius: 30px;
        display: flex;
        justify-content: center;
        align-items: center;

        }
        .find_img {
        height: 30px;
        width: auto;

        /* width:32px;
        height:32px; */
        cursor: pointer;
        }


        .box-right {
        margin: 0 auto;
        padding: 35px 0;
        padding-right: 40px;
        }

        .li{
            list-style-type: none;
            display: inline-block;
            text-align: center;
            outline : lpx dotted blue;
            margin-right: 20px;
            font-size: 30px;
        }

        /* .profile_img{
            width: 35px;
            height: 35px;
        } */


        /* a태그 속성 추가 */
        #box-right a{
        text-decoration:none;
        color: black;
        }

        #box-right ul li a{
        color: #2b2929;

        }

        /* 왼쪽 메뉴 */
        .bottom{
        /* width: 100%; */
        display: flex;
        flex-direction: row;
        }
        .left-menu{
        width: 300px; 
        /* .box_left랑 같은 width */
        height: 100vh;
        background-color: #118aa8; 
        }

        .content{
        height: 100vh;
        width : auto;
        }
    </style>

    <!-- scss를 선언할 영역 -->
    {% block scss %}
    {% endblock %}
</head>

<body>
    <!--상단부-->
    <div class="container">
        <div class="top">
            <div class="top_nav">
                <!-- 로고 -->
                <div class="box-left">
                    <div>

                        <a href="{% url 'project:project_list' %}">
                            <img class="logo_img" src="{% static 'image/logo_text.png' %}" alt="logo">

                        </a>
                    </div>
                </div>
                <!-- 서치바 -->
                <form class="box-center" action="#" method='GET'>
                    <input class="input_box" type="text" name="query" placeholder="Search">
                    <div class="input_button">
                        <input class="find_img" type="image" src="{% static 'image/find.png' %}" alt="Submit">
                    </div>

                </form>


                <!-- 유저 도구 -->
                <div class='box-right'>
                    <!-- 알림, 더보기 버튼 추가 필요 -->
                    <li class="li">
                        <a href="#">
                            프로필
                            <!-- 사용자 모델에서 이미지를 가지고 와야하는데 말이야 .. 음 .. base.html이 연결되는 view를 만들어서
                            그 view에 유저 프로필 사진을 {~}로 담아서 보내야겠다. -->

                            <!-- <img class="profile_img" width="40" height="40"></a> -->
                    </li>
                </div>
            </div>
        </div>


        <div class="bottom">
            <!-- 왼쪽 메뉴 -->
            <div class="left-menu">
                냥냥냥
            </div>

            <div class="content">
                {% block content %}
                {% endblock %}
                <!-- </div> -->
            </div>

        </div>
    </div>
</body>

</html>

MainApp/templates/MainApp/index.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>간단한 파일 관리 Fromnode</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <link href="{% sass_src 'MainApp/CSS/Index/index.scss' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container_main"> 
        <div class="menu_Bar">
            <div class="logo"><img src="{% static 'MainApp/image/fn_logo.png' %}" alt="로고" class="logo_Text"></div>
            <div class="menu_Button">
                <a class="menu_Btn" href="#"></a>
                <a class="menu_Btn" href="#"></a>
                <a class="menu_Btn" href="#"></a>
            </div>
            {% if user.is_authenticated %}
                <button class="login_Btn"><a class="logout_Text" href="{% url 'user:logout'%}" style="color:white">Logout</a></button>
            {% else %}
                <button class="login_Btn"><a class="login_Text" href="{% url 'user:login'%}">Login</a></button>
            {% endif %}
        </div>
        <div class="main_Contents">
            <div class="section1">
                <div class="section1_Left">
                    <span class="title">세상에서 가장 간단한<Br>파일 관리 서비스</span> 
                    {% if user.is_authenticated %}    
                        <button class="project_Button"><a class="project_Text" href="{% url 'project:project_list'%}">My Project</a></button>
                    {% else %}
                        <button class="project_Button"><a class="project_Text" href="{% url 'user:login'%}">Login</a></button>
                        <!-- <button class="login_Button"><span class="login_Text">Login</span></button> -->
                    {% endif %}
                    <!-- {#% if hidden == 0 %#} -->
                    <!-- <div class="loginModal">
                        <div class="modal_Overlay"></div>
                        <div class="modal_Contents">
                            <form method="POST" action="{% url 'user:login' %}" class="login">
                                {% csrf_token %}
                                <img src="{% static 'MainApp/image/fn_symbol.png' %}" alt="로고" class="login_logo loginbox">
                                <input class="loginbox" type="text" name="username" placeholder="아이디">
                                
                                <input class="loginbox" type="password" name="password" placeholder="비밀번호">

                                <button class="loginbox" type="submit">Log in</button>
                                <p class='message'>{{message}}</p>
                                <span class="ToGoSignup">아직 계정이 없다면? <a class="ToGoSignup_A" href="{% url 'user:signup' %}">가입하기</a></span>
<br>
                            </form>   
                        </div>
                    </div> -->
                </div>
                    <!-- {#% else %#} -->
                    <!-- <div class="loginModal hidden">
                        <div class="modal_Overlay"></div>
                        <div class="modal_Contents">
                            <form method="POST" action="{% url 'user:login' %}" class="login">
                                {% csrf_token %}
                                <img src="{% static 'MainApp/image/fn_symbol.png' %}" alt="로고" class="login_logo loginbox">
                                <input class="loginbox" type="text" name="username" placeholder="아이디">
                                
                                <input class="loginbox" type="password" name="password" placeholder="비밀번호">

                                <button class="loginbox" type="submit">Login</button>
                                
                                <span class="ToGoSignup">아직 계정이 없다면? <a class="ToGoSignup_A" href="{% url 'user:signup' %}">가입하기</a></span>
<br>
                            </form>   
                        </div>
                    </div> -->
                </div>
                    <!-- {#% endif %#} -->
        
        </div>
        <!-- <div class="main_Footer">
            <Div class="main_Footer_Left">
                <span>FromNode</span>
                <img src="{% static 'MainApp/image/logo_text.png' %}" alt="로고" class="logo_Text" style="border:1px solid white;">
            </Div>
            <Div class="main_Footer_Right">
                <span class="main_Footer_Text">팀 이름 : 옹헤야Lab</span>
                <span class="main_Footer_Text">문의 : fromNode </span>
            </Div>
        </div> -->
    </div>
    <script src="{% static 'MainApp/JS/index.js' %}">
    </script>
</body>
</html>

MainApp/templates/MainApp/test.html
테스트