FileApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="file"
urlpatterns = [
    path('file_list/<str:proj_Code>', views.show_file_list, name="file_list"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
    #path('create_invite_url/<str:pro_code>', views.create_invite_url, name="invite"),
    path('add_notice/', views.add_notice, name='add_notice')
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views
import explorer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
    #path('explorer/', include('explorer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

NodeApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'node'
urlpatterns = [
    # path('node_list/<int:file_Code>', views.CreateTree, name="node_list"),
    path('node_list/<str:proj_Code>', views.node_list, name="node_list"),
    path('node_detail/<str:node_Code>', views.node_detail, name="node_detail"),
    path('create_node/',views.create_node, name='create_node'),
    path('changeNodeInfo/', views.changeNodeInfo, name="changeNodeInfo"),
    path('download/<str:pk>',views.download_view,name='download'),
    path('node_comment_create/<node_Code>',
         views.node_comment_create, name="node_comment_create"),
    path('comment_mention/',views.mentionable_member_json, name='mentionable_member_json'),
    path('submit/', views.comment_submit, name="comment_submit"),
    path('load_comment/', views.load_comment, name="load_comment"),
    path('load_node_data/', views.load_node_data, name="load_node_data"),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ProjectApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('project_list/', views.show_project_list, name="project_list"),
    path('project_detail/', views.show_project_detail, name="project_detail"),
    path('project_checkcode/',views.project_checkcode, name='project_checkcode'),
    path('project_create',views.project_create,name='project_create'),
    path('project_likeornot/<str:project_Code>',views.likeornot,name='project_likeornot'),
    path('error/', views.error, name='error'),
    path('create/<str:project_Code>', views.create_invite_url, name='create_invite_url'),
    path('invite/<str:project_Code>', views.confirm_project_checkin, name='confirm_project_checkin'),
    path('project_checkin/', views.project_checkin, name='project_checkin'),
    path('already_exist/', views.already_exist, name='already_exist'),
    # path('proj_contributions/<str:project_Code>',views.proj_contributions, name = 'proj_contributions'),

    # path('form_create_project/', views.form_create_project, name="form_create_project"),
    # path('create_project/', views.create_project, name="create_project"),
]

ProjectApp/models.py
import string
from datetime import datetime
from random import choice

from django.contrib.auth.models import User
from django.db import models
from NodeApp.models import Nodes


def random_code():
    arr = [choice(string.ascii_letters) for _ in range(8)]
    Code = ''.join(arr)
    return Code

class Projects(models.Model):
    objects = models.Manager()
    Code = models.CharField(max_length=255,default=random_code, unique=True)
    name = models.CharField(max_length=255)
    start_date = models.DateTimeField(default = datetime.now, blank = True, null=True)
    due_date = models.DateTimeField(blank = True, null=True)
    description = models.TextField(max_length= 20000, blank = True)
    unliked_members = models.ManyToManyField(User,blank = True, related_name ='Joined_Unliked_Projects')
    liked_members = models.ManyToManyField(User,blank = True, related_name ='Joined_Liked_Projects')
    Proj_Nodes = models.ManyToManyField(Nodes,blank = True, related_name ='ProjNode')
    def __str__(self):
        return self.name
        

class proj_with_user(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, db_column="user_id")
    proj_id = models.ForeignKey(Projects, on_delete=models.CASCADE, db_column="proj_id")

ProjectApp/views.py
import random
from datetime import datetime, timedelta

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from FileApp.models import Files
from NodeApp.models import Node_Comment, Nodes
from notifications.signals import notify
from UserApp.models import Profile

from .models import Projects, proj_with_user

# User 모델 불러오기
# 불러온 User 모델의 Projects 불러오기
# 불러온 Projects를 슬라이싱, 이후 이걸 포함하는지 아닌지 대조!

def show_project_list(request):
    #Page 파라미터
    page = request.GET.get('page', '1')
    # 모든 프로젝트의 모든 member를 순차 조회
    if request.user.is_authenticated:
        User = request.user
        unliked_proj = User.Joined_Unliked_Projects.all()
        liked_proj = User.Joined_Liked_Projects.all()
        all_proj = unliked_proj | liked_proj
        # paginator = Paginator(all_proj, 4)  # 페이지당 10개씩 보여주기
        # page_obj = paginator.get_page(page)
        proj_obj = all_proj
    empty = ''
    if len(proj_obj) == 0:
        empty = '참여중인 프로젝트가 없습니다'
    today = datetime.today()
    contents = {
        'proj_obj' : proj_obj,
        'empty':empty, 
        'today':today,
        'proj_obj_all':all_proj,
        'like_proj':liked_proj
    }
    return render(request, 'ProjectApp/project_list.html', contents)

def show_project_detail(request):
    # project에 소속된 file들이 보여지는 detail화면으로 슝 !
    return render(request, 'FileApp/file_list.html')

def project_checkcode(request):
    Project = Projects.objects.all()
    if request.user.is_authenticated:
        proj_obj = Projects.objects.filter(members = request.user)
    Project_Codes = []
    for i in Project:
        Project_Codes.append(i.Code)
    if request.POST['Code'] in Project_Codes:
        Join_Project = Projects.objects.get(Code=request.POST['Code'])
        Owner = Join_Project.members.all()[0]
        recipients = User.objects.get(username = Owner)
        notify.send(request.user,recipient = recipients,verb = Join_Project.Code, description = 1)
        
        #이후는 알림 기능 배우고! Owner_User = User.objects.get(Username=Join_Project.whoIsOwner)
        # 코드를 보내면서, 동시에 해당 코드를 가진 프로젝트의 오너한테 알림을 보낼것!
        message = Join_Project.name,"프로젝트에 대한 참가 요청이 전송되었습니다!"
    else:
        message = "해당 코드를 지닌 프로젝트가 존재하지 않습니다"
        
    return render(request, 'ProjectApp/project_list.html', {'proj_obj' : proj_obj,'message': message})

def likeornot(request ,project_Code):
    code = project_Code
    User =request.user
    proj_obj = Projects.objects.get(Code=code)
    unliked_proj = User.Joined_Unliked_Projects.all()
    if  proj_obj in unliked_proj:
        proj_obj.unliked_members.remove(User)
        proj_obj.liked_members.add(User)
        proj_obj.save()
    else:
        proj_obj.liked_members.remove(User)
        proj_obj.unliked_members.add(User)
        proj_obj.save()
    return redirect('/project/project_list/')



        # 파일 업로드 오너 유저 불러오기
        # 업로드 점유율 체크


# def proj_contributions(request,project_Code):
#     if request.user.is_authenticated:
#         t_comment_num_ver_user = []
#         t_node_timeline_gap = []
#         t_file_upload_ver_user = []

        
        
#         objects ={

#         }

#         return render(request, 'ProjectApp/proj_contributions.html', objects)

#     else:
#         return render(request,'MainApp/index.html')

    

# def form_create_project(request):
#     return render(request,'ProjectApp/form_create_project.html')

# def create_project(request):
#     proj_obj = Projects()
#     proj_obj.Code = random.randint(0,0xffffff)
#     proj_obj.name = request.GET['projectName']
#     proj_obj.whoIsOwner = User.objects.get(username = 'sea')
#     proj_obj.save()
#     return redirect('project_list')

# def create_project(request):
#     proj_obj = Projects()
#     proj_obj.Code = random.randint(0,0xffffff)
#     proj_obj.name = request.GET['projectName']
#     proj_obj.whoIsOwner = User.objects.get(username = 'sea')
#     proj_obj.save()
#     return redirect('project_list')

# def logout(request):
#     auth.logout(request)s
#     return redirect('/')

def project_create(request):

    if request.method == 'POST':
        user = request.user
        proj_obj = Projects()
        proj_obj.name = request.POST['name']
        proj_obj.save()
        proj_obj.unliked_members.add(user)
        proj_obj.save()
        User_Profile = Profile.objects.get(user=request.user)
        User_Profile.save()
        
        return redirect('project:project_list')
        '''
        try:
            p_w_u_obj =proj_with_user();
            p_w_u_obj.proj_id = Projects.objects.get(name=proj_obj.name)
            p_w_u_obj.user_id = user
            p_w_u_obj.save()
        except:
            Projects.objects.last.delete()
            return redirect('project:error')
        '''
    else:
        return redirect('project:project_list')

def create_invite_url(request):
    project_Code = request.GET['project_Code']
    return render(request, 'ProjectApp/create_invite_url.html', {'project_Code':project_Code})

    
def error(request):
    return render(request, 'ProjectApp/error.html')


def already_exist(request):
    return render(request, 'ProjectApp/already.html')


def confirm_project_checkin(request, project_Code):
    target_project = Projects.objects.get(Code = project_Code)
    return render(request, 'ProjectApp/confirm_project_checkin.html', {'target_project':target_project})


def project_checkin(request):
    print("0")
    if request.method == 'POST':
        print("post메써드는 맞아")
        project_code = request.POST['project_code']
        if request.user.is_authenticated:
            print("User authenticated 확인")
            user = request.user
            project_obj = Projects.objects.get(Code=project_code)
            project_member = proj_with_user.objects.filter(proj_id = project_obj.id)
            print("프로젝트 검색 완료")
            detected = False
            for member in project_member:
                if member.user_id == user.id: #내가 안속해있는 프로젝트인지 확인
                    detected = True
                    break
                else:
                    pass
            if detected == True:
                return redirect('project:already')
            else:
                print("저 프로젝트에 나 없네")
                project_obj.unliked_members.add(user)
                project_obj.save()
                return redirect('index')
        else:
            return redirect('index')
    else:
        return redirect('index')
    

ProjectApp/templates/ProjectApp/create_invite_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    fromnode.com/invite/{{project_Code}} 를 복사해서 친구에게 보내주세여!
</head>
<body>
    
</body>
</html>

ProjectApp/templates/ProjectApp/form_create_project.html
<!-- {% extends 'base.html' %}
{% load sass_tags %}
{% block body %}
<button><a href="{ url 'show_project' }">프로젝트 리스트로 가기</a></button>
    <form action= "{ url 'create_project' }">
        프로젝트 이름<br>
        <input type="text" size="15" name="projectName"/><br/>
        <input type="submit" id="btn" value="생성하기"/>
    </form>
    {% endblock %} -->

    hi

ProjectApp/templates/ProjectApp/project_list.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

<!-- scss를 선언할 영역 -->
{% block scss %}
<link href="{% sass_src 'ProjectApp/CSS/project_list.scss' %}" rel="stylesheet" type="text/css">
<link href="{% sass_src 'ProjectApp/CSS/modal.scss' %}" rel="stylesheet" type="text/css">
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="header bg-primary pt-4">


    <div class="container-fluid">
        <div class="row mb-5">
            <div class="col-lg-6 col-7 d-flex align-items-center">
                <h6 class="h1 text-white d-inline-block mb-0">{{username}}'s Project List</h6>
            </div>
            <div class="col-lg-6 col-5 text-right">
                <button class="btn btn-icon btn-secondary" type="button" data-toggle="modal" data-target="#projectModal">
                    <span class="btn-inner--icon"><i class="ni ni-active-40"></i></span>
                    <span class="btn-inner--text">New Project</span>
                </button>
            </div>
        </div>
        <div class="row">
            {% for proj in proj_obj %}
            <div class="col-xl-3 col-md-5">
                <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body py-4">
                        <div class="row flex-column px-2">
                            <a href="{% url 'node:node_list' proj.Code %}">
                                <span class="h3 mb-0" style="color:rgb(34, 34, 34)">{{proj.name}}</span>
                            </a>


                            <span class="text-nowrap text-sm">{{proj.start_date|date:'Y-m-d'}} ~
                                {{proj.due_date|date:'Y-m-d'}}</span>

                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- projectModal -->
<div class="modal fade" id="projectModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <form action = "{% url 'project:project_create'%}" method = 'POST' class='create_project_form'>
        {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
            <div class="modal-card  pt-0">
                <div class="row align-items-center">
                    <div class="col">
                    <h4 class="h2 mb-0 text-center">💁‍♀️ 프로젝트 생성 💁‍♀️</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-body px-5">
            <div class="form-group">
                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon3">이름</span>
                </div>
                <input type="text" name="name" class="form-control" aria-describedby="basic-addon3">

                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon3">설명</span>
                </div>
                <input type="text" name="description" class="form-control" aria-describedby="basic-addon3">
                </div>
            </div>
        </div>
        <div class="modal-body my-4">
          <div class="d-flex justify-content-center">

            <button class="btn btn-icon btn-primary" type="submit">
                <span class="btn-inner--icon"><i class="ni ni-active-40"></i></span>
                <span class="btn-inner--text">Make New Project</span>
            </button>
          </div>
        </div>
        <div class="modal-footer">
        </div>
        </form>
    </div>
  </div>
</div>
<!-- end -->
<div class="uploadModal hidden">
    <!--hidden-->
    <div class="modal_Overlay"></div>
        <div class="modal_Contents">
            <p class="modal-title">프로젝트 이름을 정해주세요 :-)</p>
            <form action = "{% url 'project:project_create'%}" method = 'POST' class='create_project_form' onsubmit="return checkForm()">
                {% csrf_token %}
                <div class="m-boxes">
                    <div class="m-box">
                        <div class="input-title">이름 :                             
                        </div>
                        <div class="write">
                            <input type='text' name='name' class='input_sec' value=''>
                        </div>
                    </div>
                    <div class="m-box">
                        <div class="input-title">설명 : </div>
                        <div class="write">
                            <input type='text' name='description' class='input_sec' value=''>
                        </div>
                    </div>
                </div>
                <p class= 'alert_text' style='color: red;'></p>
                <div class="submit">
                    <input class="uploadBtn" type='submit'  value='생성'>
                </div>
            </form>
        </div>
</div>

{% else %}
    <p class='error'>올바르지 않은 접근입니다!</p>
    <img src ="{% static 'image/logo_character.png' %}"alt="">
{% endif %}
</div>
{% endblock %}
{% block JS %}
<script>
    const openButton = document.querySelector(".openModal");
    const modal = document.querySelector(".uploadModal");
    const overlay = modal.querySelector(".modal_Overlay");
    const alert_text = document.querySelector('.alert_text');
    const toggleModal = () => {
        modal.classList.toggle("hidden");
    }
    overlay.addEventListener("click", toggleModal);
    openButton.addEventListener("click", toggleModal);
    const likeornot = document.querySelectorAll('#likeornot');
    var arr = new Array();
    for (var i=0; i<likeornot.length; i++){
        arr[i] = likeornot[i].getAttribute('class');
    }
    var res = {};
    arr.sort();
    for(var value in arr){
        var index = arr[value];
        res[index] = res[index] == undefined ? 1:res[index]+=1;
    }
    console.log(res)
    for(var value in res){
        if(res[value]==1){
            img = "{% static 'Projectapp/image/star_off.png' %}";
            const a = document.getElementsByClassName(value);
            a[0].setAttribute('src', img);
        }
        else if (res[value]==2){
            img = "{% static 'Projectapp/image/star_on.png' %}";
            const a = document.getElementsByClassName(value);
            console.log(value,a)
            a[0].setAttribute('src', img);
            a[1].setAttribute('src',img);
        }
    }
    // var comp_arr1 = new Set(arr);
    // var comp_arr2 = new Array(comp_arr1);
    // console.log(arr,comp_arr2)
    // var final_arr = arr-comp_arr2;
    // console.log(final_arr);
    // for (var i=0; i<likeornot.length; i++){
    //     if(likeornot[i].getAttribute('class') == 'False'){
    //         img = "{% static 'Projectapp/image/star_off.png' %}";
    //         likeornot[i].setAttribute('src', img);
    //     } 
    //     else if(likeornot[i].getAttribute('class') == 'True'){
    //         img = "{% static 'Projectapp/image/star_on.png' %}";
    //         likeornot[i].setAttribute('src', img);
    //     }
    //     else{
    //         console.log(likeornot[i].getAttribute('class'));
    //         continue;
    //     }
    // }

        

    function checkForm(){
        const form = document.querySelector(".create_project_form");
        names = form.name;
        description = form.description;

        if(names.value == ""){
            alert_text.innerHTML ="제목란을 채워주세요"
            form.name.focus();
            return false;
        }
        else if(description.value ==""){
            alert_text.innerHTML ="설명란을 채워주세요"
            form.description.focus();
            return false;
        }
        else return true;

    }
</script>
{% endblock %}